name: 提交申诉工单
description: 误警告、误封禁等申诉或检举揭发
title: "申诉："
labels: ["streack","appeal"]
assignees:
  - kdxiaoyi
  - kdxhub
body:

  - type: checkboxes
    id: notice
    attributes:
      label: 您已知悉并确认：
      options:
        - label: 该模板适用于**服务器**的相关问题
          required: true
        - label: 已预先查阅[相关文档](https://mc.kdxiaoyi.top/Streack/doc)和检索相似ISSUE
          required: true
        - label: "此工单向其它人公开可见，并确认不使用[邮件等私密工单渠道](https://mc.kdxiaoyi.top/Streack/#issue)。"
          required: true
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: 工单类型
      description: 选择您发起此工单的目的
      multiple: false
      options:
        - 申诉误警告、误处罚、误封禁
        - 举报玩家作弊
        - 举报滥用职权
    validations:
      required: true

  - type: input
    id: target
    attributes:
      label: 申诉谁？
      description: |
        您为谁申诉，或者您要举报谁？
        * 基岩版玩家名请加“-”前缀，不含引号
    validations:
      required: true

  - type: textarea
    id: request
    attributes:
      label: 诉求为？
      description: 您发起此工单的目的是什么？（可选）
      placeholder: 我想要……
    validations:
      required: false

  - type: textarea
    id: reason
    attributes:
      label: 理由是？
      description: |
        填写您的诉求的理由。
        * 可以上传图片、视频、Replay录像文件、聊天记录等佐证您的诉求的合理性。
        * 时间若无提及默认为东八区时间。说明时间有助于调查。
        * **证据越多、论述越充分、表述越客观那么工单受理概率越大。**
      placeholder: 因为……
    validations:
      required: true

  - type: checkboxes
    id: notice
    attributes:
      label: 您承诺：
      options:
        - label: 保证所提供的相关材料的真实性与合理性
          required: true
    validations:
      required: true

  - type: textarea
    id: addition
    attributes:
      label: 附言
    validations:
      required: false

