blank_issues_enabled: false
contact_links:
  - name: 浏览文档
    url: "https://kdxiaoyi.top/Streack/doc"
    about: 有的时候文档里写的很明白，真的。
  - name: 加入QQ群
    url: "https://kdxiaoyi.top/Streack/#qqun"
    about: 闲聊或是接收动态